### ISSUE TITLE
Splout SQL / Pangool doesn't play well with CDH4

### ISSUE THREAD

**Issue by pereferrera** [datasalt/splout-db#21]
It must be something straight-forward, but needs to be tested and verified.

**Comment by girishprb** [comment]
hello,
i am running hadoop 2.2 and splout 0.3. when i run the command below mentioned command,

hadoop jar /usr/local/splout/splout-*-hadoop*.jar simple-generate --input /city.csv --output \
  database-files --tablespace city_pby_country_code --table city --separator , --escape \\ --quotes \
  \"\"\" --nullstring \\N --schema \
  "id:int,name:string,country_code:string,district:string,population:int" --partitionby country_code \
  --partitions 4 

i get the following error.

15/04/23 07:27:20 INFO mapreduce.Job: Task Id : attempt_1429787320781_0006_r_000003_2, Status : FAILED
Error: java.io.FileNotFoundException: File /tmp/hadoop-girish/nm-local-dir/usercache/girish/appcache/application_1429787320781_0006/splout_task_attempt_1429787320781_0006_r_000003_2.1/3.db does not exist


please help, I have no clue why this is happening.

Thanks in advance

**Comment by ivanprado** [comment]
You must execute the command from the Splout installation folder, otherwise
it won't work.

cd $SPLOUT_HOME
hadoop jar splout-*-hadoop*.jar simple-generate --input /city.csv --output \
database-files --tablespace city_pby_country_code --table city --separator
, --escape \ --quotes \
\"\"\" --nullstring \N --schema \
"id:int,name:string,country_code:string,district:string,population:int"
--partitionby country_code \
--partitions 4

Regards,
Iván

2015-04-23 13:49 GMT+02:00 Girish Prabhu <notifications@github.com>:

> hello,
> i am running hadoop 2.2 and splout 0.3. when i run the command below
> mentioned command,
>
> hadoop jar /usr/local/splout/splout-*-hadoop*.jar simple-generate --input
> /city.csv --output \
> database-files --tablespace city_pby_country_code --table city --separator
> , --escape \ --quotes \
> \"\"\" --nullstring \N --schema \
> "id:int,name:string,country_code:string,district:string,population:int"
> --partitionby country_code \
> --partitions 4
>
> i get the following error.
>
> 15/04/23 07:27:20 INFO mapreduce.Job: Task Id :
> attempt_1429787320781_0006_r_000003_2, Status : FAILED
> Error: java.io.FileNotFoundException: File
> /tmp/hadoop-girish/nm-local-dir/usercache/girish/appcache/application_1429787320781_0006/splout_task_attempt_1429787320781_0006_r_000003_2.1/3.db
> does not exist
>
> please help, I have no clue why this is happening.
>
> Thanks in advance
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datasalt/splout-db/issues/21#issuecomment-95558656>.
>



-- 
Iván de Prado
CEO & Co-founder
www.datasalt.com

**Comment by girishprb** [comment]
Hello Ivan,
It worked thank you.
I am facing an other problem while deploying the table space.
When i run the command 
hadoop jar splout-*-hadoop*.jar deploy --root database-files --tablespaces city_pby_country_code \
  --replication 2 --qnode http://localhost:4412.
the deployment is failing with the error 
" [java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.hdfs.DistributedFileSystem not found at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:1720) at ....."

my classpath has usr/local/hadoop/share/hadoop/hdfs/hadoop-hdfs-2.2.0.jar and the core-site.xml has the following configuration 
<configuration>
<property>
<name>fs.default.name</name>
<value>hdfs://localhost:54310</value>
</property>
<property>
   <name>fs.file.impl</name>
   <value>org.apache.hadoop.fs.LocalFileSystem</value>
   <description>The FileSystem for file: uris.</description>
</property>
<property>
   <name>fs.hdfs.impl</name>
   <value>org.apache.hadoop.hdfs.DistributedFileSystem</value>
   <description>The FileSystem for hdfs: uris.</description>
</property>
</configuration>

is there anything i am missing out on. please help

**Comment by girishprb** [comment]
problem fixed, had not properly set up SPLOUT_CLASSPATH

**Comment by johnboy14** [comment]
I get the following error when trying to load the example data on my mac.  I've tried the following fixes above.
Caused by: java.io.FileNotFoundException: File /usr/local/Cellar/hadoop/hdfs/tmp/mapred/local/localRunner/johnervine/jobcache/job_local1557350574_0002/attempt_local1557350574_0002_r_000000_0/splout_task_attempt_local1557350574_0002_r_000000_0.1/0.db does not exist
	at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:534)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:747)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:524)
	at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:409)
	at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:337)
	at org.apache.hadoop.fs.FileSystem.copyFromLocalFile(FileSystem.java:1905)
	at org.apache.hadoop.fs.FileSystem.copyFromLocalFile(FileSystem.java:1873)
	at org.apache.hadoop.fs.FileSystem.moveFromLocalFile(FileSystem.java:1860)
	at org.apache.hadoop.fs.FileSystem.completeLocalOutput(FileSystem.java:1996)
	at com.splout.db.hadoop.engine.SploutSQLProxyOutputFormat$1.close(SploutSQLProxyOutputFormat.java:118)
	at org.apache.hadoop.mapred.ReduceTask$NewTrackingRecordWriter.close(ReduceTask.java:550)
	at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:629)
	at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:389)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$ReduceTaskRunnable.run(LocalJobRunner.java:319)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)

**Comment by pereferrera** [comment]
Hi john, what version of Hadoop are you using?

**Comment by johnboy14** [comment]
Hi pereferrera, I'm currently trying this with Hadoop version 2.6.0

**Comment by ivanprado** [comment]
Hi John,

Please, try with this Snapshot version:
http://clinker.datasalt.com/nexus/service/local/repositories/snapshots/content/com/splout/db/splout-distribution/0.3.1-SNAPSHOT/splout-distribution-0.3.1-20150616.152133-37-mr2.tar.gz

The real error is being masked so we cannot say what is happening (The
problem is usually caused by not executing job from the Splout installation
folder, but you said you have tried). Execute the job with this version and
tell us which exception you get.

Regards,
Iván

2015-06-19 11:35 GMT+02:00 john ervine <notifications@github.com>:

> Hi pereferrera, I'm currently trying this with Hadoop version 2.6.0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datasalt/splout-db/issues/21#issuecomment-113446169>.
>



-- 
Iván de Prado
CEO & Co-founder
www.datasalt.com

**Comment by ivanprado** [comment]
Are you use a particular distribution (Cloudera, HortonWorks)? Which
version? Which Hive version are you using?

Regards,
Iván

2015-06-19 12:01 GMT+02:00 Iván de Prado <ivan@datasalt.com>:

> Hi John,
>
> Please, try with this Snapshot version:
> http://clinker.datasalt.com/nexus/service/local/repositories/snapshots/content/com/splout/db/splout-distribution/0.3.1-SNAPSHOT/splout-distribution-0.3.1-20150616.152133-37-mr2.tar.gz
>
> The real error is being masked so we cannot say what is happening (The
> problem is usually caused by not executing job from the Splout installation
> folder, but you said you have tried). Execute the job with this version and
> tell us which exception you get.
>
> Regards,
> Iván
>
> 2015-06-19 11:35 GMT+02:00 john ervine <notifications@github.com>:
>
>> Hi pereferrera, I'm currently trying this with Hadoop version 2.6.0
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/datasalt/splout-db/issues/21#issuecomment-113446169>.
>>
>
>
>
> --
> Iván de Prado
> CEO & Co-founder
> www.datasalt.com
>



-- 
Iván de Prado
CEO & Co-founder
www.datasalt.com

**Comment by johnboy14** [comment]
I am not using particular distribution mentioned.  I installed Hadoop on my mac using Homebrew.  I haven't installed HIVE, I was under the assumption it came with HIVE.  I'm very new to Hadoop, so excuse my ignorance.  I will try the mentioned distribution above ivan and see where it gets me. 

brew install hadoop

**Comment by johnboy14** [comment]
Thanks, this distribution worked for me.  One thing to note I was getting the following error on startup.

cannot load library: java.lang.UnsatisfiedLinkError: no sqlite4java-osx-x86_64-0.282 in java.library.path

This was corrected by copying the following jnilib libraries into the native directory on the splout distribution.  See post for details.  
https://groups.google.com/forum/#!topic/sploutdb-users/ihioT60jpQQ

**Comment by ivanprado** [comment]
Nice! Thanks John.

2015-06-20 10:36 GMT+02:00 john ervine <notifications@github.com>:

> Thanks, this distribution worked for me. One thing to note I was getting
> the following error on startup.
>
> cannot load library: java.lang.UnsatisfiedLinkError: no
> sqlite4java-osx-x86_64-0.282 in java.library.path
>
> This was corrected by copying the following jnilib libraries into the
> native directory on the splout distribution. See post for details.
>
> https://groups.google.com/forum/#!topic/sploutdb-users/ihioT60jpQQ
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datasalt/splout-db/issues/21#issuecomment-113730253>.
>



-- 
Iván de Prado
CEO & Co-founder
www.datasalt.com
